import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { CmsData } from '../lib/cms';

// Generated by the validated importer. Never imported by browser scripts.
const snapshotPath = resolve(process.cwd(), '.generated/cms-snapshot.json');
export const buildCmsData: CmsData | null = existsSync(snapshotPath)
  ? JSON.parse(readFileSync(snapshotPath, 'utf8')) as CmsData
  : null;
